concurrency:
    limit: 1  # This ensures only one job runs at a time

include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    # chunk_size here forces multiple chunks even for test data which better exercises some channels
    NF_WORKFLOW_OPTS: "--fastq test_data/fastq --reference test_data/ref/reference.subseq.fa.gz --threads 4 --chunk_size 100000"
    NF_IGNORE_PROCESSES: "deNovo"
    CI_FLAVOUR: "new"

docker-run:
    parallel:
        matrix:
            # Add max_parallel for each section to limit concurrency
            - MATRIX_NAME: [de-novo, amr, barcode04, mixed-species, reference-iso, de-novo-advanced_options, de-novo-bam]
              TAG: [large_ram]
              max_parallel: 1  # Add this to limit parallel jobs
            - MATRIX_NAME: [reference-based, check-model, sample-sheet]
              TAG: [""]
              max_parallel: 1  # Continue limiting parallel jobs to 1

    tags:
        - $TAG

    rules:
        # Define memory limits and conditions for specific matrix jobs
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "de-novo"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 32GB \
                  --fastq test_data/fastq --threads 3 --chunk_size 100000"
              NF_IGNORE_PROCESSES: "medakaVariant,medakaVariantHdf,makePerSampleReports"
        - if: $MATRIX_NAME == "de-novo-bam"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 32GB \
                  --bam test_data/bam --threads 4 --chunk_size 100000 --override_basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v3.5.2"
              NF_IGNORE_PROCESSES: "medakaVariant,medakaVariantHdf,makePerSampleReports"
        - if: $MATRIX_NAME == "de-novo-advanced_options"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 32GB \
                  --fastq test_data/fastq --threads 3 --chunk_size 100000 --flye_opts '--genome-size 25k'"
              NF_IGNORE_PROCESSES: "medakaVariant,medakaVariantHdf,makePerSampleReports"
        - if: $MATRIX_NAME == "amr"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 32GB \
                  --fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-bacterial-genomes/test_data/isolates_fastq --sample_sheet test_data/isolates_sample_sheet.csv --threads 3 --chunk_size 100000 --isolates --client_fields test_data/client_fields.json --override_basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v3.5.2"
              NF_IGNORE_PROCESSES: "runProkka,medakaVariant,medakaVariantHdf,makePerSampleReports"
        - if: $MATRIX_NAME == "sample-sheet"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 16GB \
              --fastq test_data/fastq --reference_based_assembly --reference test_data/ref/reference.subseq.fa.gz --threads 4 --chunk_size 100000 \
                  --sample_sheet test_data/sample_sheet.csv"
              NF_IGNORE_PROCESSES: "deNovo,assemblyStats,runProkka,makePerSampleReports"
        - if: $MATRIX_NAME == "barcode04"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 32GB \
              --fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-bacterial-genomes/test_data/isolates_fastq/barcode04 \
                  --threads 3 --chunk_size 100000 --override_basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v3.5.2"
              NF_IGNORE_PROCESSES: "alignReads,readStats,coverStats,splitRegions,\
                  medakaConsensus,medakaNetwork,medakaVariant,medakaVariantHdf,makeReport,runProkka,makePerSampleReports"
        - if: $MATRIX_NAME == "mixed-species"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 32GB \
              --fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-bacterial-genomes/test_data/isolates_fastq --sample_sheet test_data/isolates_mixed_sample_sheet.csv --threads 3 --chunk_size 100000 --isolates --override_basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v3.5.2"
              NF_IGNORE_PROCESSES: "runProkka,medakaVariant,medakaVariantHdf"
        - if: $MATRIX_NAME == "reference-iso"
          variables:
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 16GB \
              --fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-bacterial-genomes/wf-bacterial-genomes-demo/isolates_fastq/barcode02 --reference_based_assembly --reference test_data/ref/salmonella_reference.fa.gz --threads 4 --chunk_size 100000 --isolates --override_basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v3.5.2"
              NF_IGNORE_PROCESSES: "deNovo,runProkka"
# reminder: update AUX_IMAGE_TAG if the aux container package versions are changed
release-prokka:
    extends: .aux-container
    variables:
        AUX_IMAGE_NAME: "prokka"
        AUX_IMAGE_ENVFILE: "environment_prokka.yaml"
        AUX_IMAGE_TAG: "1.14.5"

